### ISSUE TITLE
Error parsing file after ~75 gb of json

### ISSUE THREAD

**Issue by 69b69t** [mlomb/chat-analytics#102]
after about 75 gb of json the program fails with the error "Error parsing file"
![image](https://github.com/mlomb/chat-analytics/assets/90358001/e5f4ff0d-810c-4f67-b3db-c62d538c03be)

note that the file itself does not have errors, as parsing the single file works without issue
![image](https://github.com/mlomb/chat-analytics/assets/90358001/c951b0ae-a432-4c5c-9fd3-b3a660e96a6e)

**Comment by HopperElec** [comment]
Oh, wow! I did tell mlomb to expect larger reports, but even I wasn't expecting nearly that much lol. I'm surprised it managed as much as it did! I'd imagine this is just your browser running out of memory, both due to the size of the exports and due to the ambiguous error (the kind of error I only usually see for memory-related issues). Only solution I can think for this would be to use IndexedDB for overly large data. Storing to disk will be slower, so I don't think it should be the default. Perhaps there will be a way to catch a memory error before it happens (don't want to catch it as it happens, otherwise there'll be no memory left for handling the exception!). Another benefit of storing large aggregate data in memory would be that it can be picked back up later (so you don't need to have it running for 80 minutes straight!), and so it might actually be better to just start storing to disk as soon as a threshold (perhaps 100MB?) is reached

**Comment by mlomb** [comment]
As @HopperElec said, I'm just surprised that it lasted so long and managed to process 52M messages without crashing. There is no way to have all that data in a single report, it's just too big for chat-analytics.
You can have multiple reports combining up to 15M perhaps, but I wouldnt go further.

-----

Maybe, just MAYBE using the library to process all the files MAY work, but the report would be huge and the browser may refure to load it. Still worth trying.

**Comment by mlomb** [comment]
Closing since `chat-analytics` will not be able to process exports of this magnitude, at least for now
