### ISSUE TITLE
Everything is processed in your browser.  Lock No data leaves your device.

### ISSUE THREAD

**Issue by veeud** [mlomb/chat-analytics#103]
Why does the site make post request to an API (https://p.chatanalytics.app/api/event) when I try to process my data. Is there a way to use it fully offline?

Would be kind if someone is willing to help me with this. Thanks it advance.

**Comment by mlomb** [comment]
Thanks for using chat-analytics!
That request is sending anonymized and trucated analytics to (a self hosted version of) [Plausible](https://plausible.io), which doesn't use cookies and its privacy friendly.
Apart from general events (like select platform, start a report generation), we specifically track the following when your report is done:

https://github.com/mlomb/chat-analytics/blob/055c68c78e12c6e3f32cb9137135e426c49a64bf/app/components/Steps.tsx#L104-L113

The category function truncates the data so its not identifiable:

https://github.com/mlomb/chat-analytics/blob/055c68c78e12c6e3f32cb9137135e426c49a64bf/assets/Plausible.ts#L61-L66

This is useful for me to know which platforms are being used, what kind of sizes to expect, how much time is the generation taking, and which are the most used languages, among other things.

All stats are open for you to check them out (as stated in the README): https://p.chatanalytics.app/chatanalytics.app?period=12mo

Just to be clear **NO DATA YOU UPLOAD TO THE SITE IS BEING SENT**, everything is processed in your browser.

-------

> Is there a way to use it fully offline?

Not for now but will be possible in the future. For now you can use the library to generate the report (since it doesn't send requests), but the report itself will trigger a pageview.

**Comment by HopperElec** [comment]
Thought I'd add that a config option is planned for toggling analytics for a generated report https://github.com/mlomb/chat-analytics/issues/74 If you're still concerned about these analytics, you could consider DNS mapping p.chatanalytics.app to something else like 127.0.0.1 via your hosts file since this is the only domain name used

**Comment by veeud** [comment]
> Thanks for using chat-analytics!
> That request is sending anonymized and trucated analytics to (a self hosted version of) [Plausible](https://plausible.io), which doesn't use cookies and its privacy friendly.
> Apart from general events (like select platform, start a report generation), we specifically track the following when your report is done:
> 
> https://github.com/mlomb/chat-analytics/blob/055c68c78e12c6e3f32cb9137135e426c49a64bf/app/components/Steps.tsx#L104-L113
> 
> The category function truncates the data so its not identifiable:
> 
> https://github.com/mlomb/chat-analytics/blob/055c68c78e12c6e3f32cb9137135e426c49a64bf/assets/Plausible.ts#L61-L66
> 
> This is useful for me to know which platforms are being used, what kind of sizes to expect, how much time is the generation taking, and which are the most used languages, among other things.
> 
> All stats are open for you to check them out (as stated in the README): https://p.chatanalytics.app/chatanalytics.app?period=12mo
> 
> Just to be clear **NO DATA YOU UPLOAD TO THE SITE IS BEING SENT**, everything is processed in your browser.
> 
> -------
> 
> > Is there a way to use it fully offline?
> 
> Not for now but will be possible in the future. For now you can use the library to generate the report (since it doesn't send requests), but the report itself will trigger a pageview.

Why is it useful for you though (stats like size and message count) if everything is done clide side. Just out of curiosity?

**Comment by veeud** [comment]
> Thought I'd add that a config option is planned for toggling analytics for a generated report (relevant issue is https://github.com/mlomb/chat-analytics/issues/74 so you can subscribe to that if you'd like updates). If you're still concerned about these analytics, you could consider DNS mapping p.chatanalytics.app to something else like 127.0.0.1 (localhost) via your hosts file since this is the only domain name used

Will look forward to that!

**Comment by veudal** [comment]
> Thought I'd add that a config option is planned for toggling analytics for a generated report (relevant issue is #74 so you can subscribe to that if you'd like updates). If you're still concerned about these analytics, you could consider DNS mapping p.chatanalytics.app to something else like 127.0.0.1 (localhost) via your hosts file since this is the only domain name used

Are there any updates on this?

**Comment by mlomb** [comment]
Not yet unfortunately, we still need to add an option in the UI. You can always clone and add a return in the function:

https://github.com/mlomb/chat-analytics/blob/e09cda3267c683ae44fdfc73aa718870a15554f2/assets/Plausible.ts#L7

-----

I just finished my master thesis and have other projects in the way, so can't promise.
I want to get to chat-analytics next year, have some big changes in mind (pipeline).

**Comment by mlomb** [comment]
> Why is it useful for you though (stats like size and message count) if everything is done clide side. Just out of curiosity?

To give some examples:
- We can check the error rates of each of the platforms. It is too high tbh
- How many messages per report people have, so we know what to aim for. Right now I am at 20M, and 99% of reports are under that.
- Most people don't analyze more than one channel for example (DMs), so the whole channel UI is underutilized. This hints mabe the UI should change when there is only one channel.
- Which languages is the identifier detecting / people most using. This may hint that we need more advanced tokenizers for some languages (not the case for now)
- Are reports generated big enough? Do we need better compression or we can change it for more accuracy?

Those kinds of things

**Comment by veudal** [comment]
> Not yet unfortunately, we still need to add an option in the UI. You can always clone and add a return in the function:
> 
> https://github.com/mlomb/chat-analytics/blob/e09cda3267c683ae44fdfc73aa718870a15554f2/assets/Plausible.ts#L7
> 
> -----
> 
> I just finished my master thesis and have other projects in the way, so can't promise.
> I want to get to chat-analytics next year, have some big changes in mind (pipeline).

Will do that, thank you. I just thought it would be really nice if the report generation could be done without any internet connection (of course the page has to load initially, but after that), so that people who can't code or even those who do are sure not there data is safe.
