### ISSUE TITLE
package.json not recognized in NPX

### ISSUE THREAD

**Issue by unicodeixixixi** [mlomb/chat-analytics#105]
Hi all! I'm having troubles running 1.1.1 of chat-analytics on Windows.
This is the error im getting:
```
D:\chat-analytics-1.1.1\chat-analytics-1.1.1> npx chat-analytics
'chat-analytics' is not recognized as an internal or external command,
operable program or batch file.
```
 I've tried  looking on the internet but to no avail.

**Comment by livingflore** [comment]
1. `npm i`
2. `npm run build:node`
3. `npm run build:web`
4. in separate cmd `npx webpack serve --open`
5. then you can use `npx chat-analytics`

(without webpack running, generating a report will give you an error with missing report.html file due to cli expecting it at dist-web for some reason and not dist where it's being generated)

**Comment by unicodeixixixi** [comment]
Thanks for the quick reply. I'll test it and if it works i'll close the issue.
