### ISSUE TITLE
Show positive/negative content/authors?

### ISSUE THREAD

**Issue by apollo-gl** [mlomb/chat-analytics#108]
I would love to be able to see exactly what people are saying and who is saying it, versus just seeing a % or # of positive and negative sentiment.

**Comment by HopperElec** [comment]
I previously asked about positive-negative authors [here](https://github.com/mlomb/chat-analytics/issues/57) but it was closed and moved into [this issue](https://github.com/mlomb/chat-analytics/issues/56). Positive/negative content is also something I previously asked about [here](https://github.com/mlomb/chat-analytics/issues/25) but that one was closed because it simply isn't feasible since raw message content is not stored internally meaning there would be no useful way to display this information.

**Comment by apollo-gl** [comment]
thank you
