### ISSUE TITLE
Emoji Sentiment scores get processed as string

### ISSUE THREAD

**Issue by chipskram** [mlomb/chat-analytics#116]
While trying to build a sentiment ranking for my messages similar to the top reacted feature, I noticed that some messages that are definitely positive ended up with a sentiment score of -128.

I've tracked the issue down to a bug regarding the scoring of emojis, as the decimal point values taken for those get processed as strings rather than numbers.

![image](https://github.com/user-attachments/assets/43b2e126-69e1-4b99-9ee3-aa358c62880f)

**Comment by mlomb** [comment]
Hey! Thanks for reporting this, fixed in [3a72ee6](https://github.com/mlomb/chat-analytics/commit/3a72ee638647420170ac48a1cc6fca13119aed59). Sentiment was stored in strings instead of numbers:

https://github.com/mlomb/chat-analytics/blob/9271c9661139d546aafff0f2335c76568531d479/assets/data/emojis/gen.js#L14

The number is truncated to 3 decimals but never converted back. Adding `parseFloat` brings them back:

https://github.com/mlomb/chat-analytics/blob/3a72ee638647420170ac48a1cc6fca13119aed59/assets/data/emojis/gen.js#L14

--------------------------

I added a test that failed before the fix and works after:

https://github.com/mlomb/chat-analytics/blob/3a72ee638647420170ac48a1cc6fca13119aed59/tests/process/nlp/Sentiment.test.ts#L20-L23

Now it should work correctly.

--------------------------

Thanks again for the finding. I was trusting too much the TypeScript typing and never checked :)

https://github.com/mlomb/chat-analytics/blob/9271c9661139d546aafff0f2335c76568531d479/pipeline/process/nlp/Emojis.ts#L7-L8
