### ISSUE TITLE
[suggestion] see which chats are negative or why sentiment analysis identified as negative

### ISSUE THREAD

**Issue by thaynos** [mlomb/chat-analytics#120]
it would be very helpful if we could see which messages were tagged as negative or positive as that could give us a deeper insight into the accuracy. perhaps maybe add a accurate or not button to further help refine the model?

**Comment by hopperelec** [comment]
I suggested this in https://github.com/mlomb/chat-analytics/issues/25, but it's sadly not possible because it would require storing the raw messages in the database which would be far too large. Also, the model isn't trained specifically for chat-analytics (chat-analytics uses [multilang-sentiment](https://github.com/marcellobarile/multilang-sentiment)) so chat-analytics isn't really able to "refine the model" (might be theoretically possible, but it would be futile and out-of-scope).
