### ISSUE TITLE
[WhatsApp] Bug with some "language words"

### ISSUE THREAD

**Issue by LHCLYT** [mlomb/chat-analytics#6]
Hey! I found a bug analyzing my WhatsApp chat.

On the "Language" window, If I search on the search bar for a very specific type of word, like "Ana", it doesn't work, I have a chat, with 600 words literally saying "Ana", and it doesn't count.

Thanks!

**Comment by LHCLYT** [comment]
Other bug: 

With some Catalan words, it doesn't found, words like: "t'estimo"

**Comment by mlomb** [comment]
Hey!

### About "Ana"
It appears to be a stopword in Latin, so it is excluded. I'm currently combining stopwords of all languages, because using the lang detected by fasttext is not that accurate.
https://github.com/mlomb/chat-analytics/blob/bdedb582c22236139d811c8ac53d5a37b051a622/pipeline/process/DatabaseBuilder.ts#L93-L98
Stopwords are here: https://github.com/mlomb/chat-analytics/blob/main/assets/data/text/stopwords-iso.json search for "ana".
Not sure if we have a solution here.

### About "t'estimo"
Can you try searching for "testimo" and "estimo"?
It's strange because manually testing for "t'estimo" with what the tokenizer uses works:
https://github.com/mlomb/chat-analytics/blob/554620139acb80964c5ae2748b6f025e6fc65490/pipeline/process/Tokenizer.ts#L50-L55
yields the expected result:
```js
"hello t'estimo world".match(/(?:\p{L}[\p{L}'0-9-]*[\p{L}0-9])|\p{L}/giu)
// ['hello', "t'estimo", 'world']
```
