### ISSUE TITLE
[Question]: How is sentiment calculated

### ISSUE THREAD

**Issue by Zo-Bro-23** [mlomb/chat-analytics#66]
One of my chats has around 20% negative messages, but I don't understand what this means. How is it determined if a message is "positive" or "negative"?

**Comment by HopperElec** [comment]
Through sentiment analysis, which is where certain words (and in this case, emojis) are assigned a value denoting how positive or negative they're considered (for example 'lovely' would be positive and 😡 would be negative). For every message, the sum of all these scores (or I believe chat-analytics rounds these scores) determines that messages sentiment. Sentiment analysis can be used to identify, for example, where arguments often happen and hence where more moderation is needed. It can also be used to identify users who only ever cause trouble or who are especially kind to other users. However, keep in mind that it's only a rough metric, there isn't a true way to calculate 'kindness' or arguments, especially since it is determined on a per-message basis so context isn't considered.

**Comment by HopperElec** [comment]
Through sentiment analysis, which is where certain words (and in this case, emojis) are assigned a value denoting how positive or negative they're considered (for example 'lovely' would be positive and 😡 would be negative). For every message, the sum of all these scores (or I believe chat-analytics rounds these scores) determines that messages sentiment. Sentiment analysis can be used to identify, for example, where arguments often happen and hence where more moderation is needed. It can also be used to identify users who only ever cause trouble or who are especially kind to other users. However, keep in mind that it's only a rough metric, there isn't a true way to calculate 'kindness' or arguments, especially since it is determined on a per-message basis so context isn't considered.

**Comment by Zo-Bro-23** [comment]
Right. Thanks for the clarification! I'm only active in DMs and Servers with less than 10 members, so this would probably not matter very much for me. One of my DMs has >9k messages, and I've only ever sent 20k messages, so that's half of all my messages on Discord! I was just wondering why I had around 20% negative for that DM, but this makes sense now. Friendly debates and slight disagreement might have contributed to that 20%. Thanks for the answer!
