### ISSUE TITLE
URL tokenization does not match GET params

### ISSUE THREAD

**Issue by UnduGT** [mlomb/chat-analytics#71]
Pressing Language will also count words that appear in links, if you have sent many of them on the server it will result in everything being full of link metadata. There is already a filtering option but it would also be helpful if you had a button to exclude links from the count.

Example:
![Screenshot from 2023-03-26 20-09-10](https://user-images.githubusercontent.com/35867985/227795643-7967921a-f70a-452b-aecc-d47affc84bc9.png)

**Comment by mlomb** [comment]
Hi! Thanks for the report!
I havent experienced this myself, you mean the small embed Discord includes after sending a link or the link itself?
The links itself should be tokenized as URLs and be completely excluded from the Language tab. Maybe the tokenizer is broken?

**Comment by HopperElec** [comment]
![image](https://user-images.githubusercontent.com/52380674/228075878-c1cf7bb3-a2b7-40df-a995-323fc08dfa39.png)
Could just add an ampersand to the character set. Also, not sure what the purpose of that non-capturing group is, or the trailing forward slash considering that's already part of the prior character set

**Comment by mlomb** [comment]
Lets go for it, do you want to open a PR?
I did not write that regex, I shamelessly stolen it from the internet 😅. It has to be revised at some point

**Comment by HopperElec** [comment]
There's quite a few issues with that regex (unnecessary grouping, TLD limited to 6 characters, TLD required, misses many characters allowed in path). I feel like it would make more sense to use a regex actually already used by one of the supported platforms, since I'm pretty sure it's anything that the platform highlights blue which we want to exclude. I already found the regex Discord uses `^(https?:\/\/[^\s<]+[^<.,:;"')\]\s])` and it is much more simple and lenient (matching many non-URLs, which I'd much prefer over not matching many URLs). I can't remember why their regex only matches the beginning of a string, but modified for ChatAnalytics it would be `https?:\/\/[^\s<]+[^<.,:;"')\]\s]`. I'll make a PR now

**Comment by mlomb** [comment]
Hey @UnduGT could you try generating the report again? (using the web app)
Thanks @HopperElec for the Regex!

**Comment by UnduGT** [comment]
Sorry for the late reply, but yes it works now exactly as it should! Perfect, thank you!
