### ISSUE TITLE
Remove misleading nicks

### ISSUE THREAD

**Issue by n3rd3x3** [mlomb/chat-analytics#78]
The exported analytics page seemingly uses the user's nickname instead of username, with their discriminator at the end. This leads to misleading and confusing data, where if a user is nicked, they can appear to be another user.

Hopefully this can be changed to instead show the proper username, instead of their nickname. Or possibly a way to chose if you want to see the nickname or username.

**Comment by HopperElec** [comment]
Discord is actually completely revamping the username system, anyways, so this can be fixed alongside that https://discord.com/blog/usernames

**Comment by HopperElec** [comment]
Also, it looks like this behaviour is intentional, I'm guessing because most exports will be of individual servers where exporters are more likely to recognise users by the nickname they use in said server

https://github.com/mlomb/chat-analytics/blob/452037f2ada3cff2fc656dc75a2938d4e3324094/pipeline/parse/parsers/DiscordParser.ts#L82-L83

**Comment by mlomb** [comment]
You are right @n3rd3x3. We should either show the username+discriminator or just the nickname, showing nickname+discriminator is just wrong.

As @HopperElec shared, since the username system is going to change anyway, we can leave it as it is for now.
